FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Set environment variable to bind to all network interfaces
ENV HOST=0.0.0.0

EXPOSE 3000

# Start the app
CMD ["npm", "start"] 