apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food-ordering-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: food-ordering-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://order-service:3003/api"
        - name: REACT_APP_AUTH_URL
          value: "http://auth-service:3001/api"
        - name: REACT_APP_RESTAURANT_URL
          value: "http://restaurant-service:3002/api"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: food-ordering-system
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP 