apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: food-ordering-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: "3006"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: service-api-key
              key: key
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: food-ordering-system
spec:
  selector:
    app: notification-service
  ports:
  - port: 3006
    targetPort: 3006
  type: ClusterIP 