apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: food-ordering-system
type: Opaque
data:
  # Base64 encoded values
  jwt-secret: eW91ci1zZWNyZXQta2V5Cg==  # your-secret-key
  mongodb-uri: bW9uZ29kYitzcnY6Ly9kYkxhc2l0aGE6ZGJVc2VyMTIzQGNsdXN0ZXIwLmQzcWFtLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMAo=  # mongodb+srv://dbLasitha:dbUser123@cluster0.d3qam.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 